

project_id = "ckvqfrppnfhoadcpqhld"

[auth]
# Enable leaked password protection
enable_leaked_password_protection = true
# Set OTP expiry to 10 minutes (600 seconds) for better security
email_otp_expiry = 600
