
import { YearlyData, DetailedYearlyData } from './types';

export const convertDetailedToStandard = (detailed: DetailedYearlyData): YearlyData => {
  return {
    year: detailed.year,
    net_sales: detailed.ventas_netas,
    other_revenue: detailed.valor_produccion - detailed.ventas_netas,
    food_cost: detailed.comida,
    food_employees: detailed.comida_empleados,
    waste: detailed.desperdicios,
    paper_cost: detailed.papel,
    crew_labor: detailed.mano_obra,
    management_labor: detailed.mano_obra_gerencia,
    social_security: detailed.seguridad_social,
    travel_expenses: detailed.gastos_viajes,
    advertising: detailed.publicidad,
    promotion: detailed.promocion,
    external_services: detailed.servicios_exteriores,
    uniforms: detailed.uniformes,
    operation_supplies: detailed.suministros_operacion,
    maintenance: detailed.reparacion_mantenimiento,
    utilities: detailed.luz_agua_telefono,
    office_expenses: detailed.gastos_oficina,
    cash_differences: detailed.diferencias_caja,
    other_controllable: detailed.varios_controlables,
    pac: detailed.pac,
    rent: detailed.renta,
    additional_rent: detailed.renta_adicional,
    royalty: detailed.royalty,
    office_legal: detailed.oficina_legal,
    insurance: detailed.seguros,
    taxes_licenses: detailed.tasas_licencias,
    depreciation: detailed.depreciaciones_amortizaciones,
    interest: detailed.intereses,
    other_non_controllable: detailed.varios_no_controlables,
    non_product_sales: detailed.ventas_no_producto,
    non_product_cost: detailed.costo_no_producto,
    draw_salary: detailed.draw_salary,
    general_expenses: detailed.gastos_generales,
    loan_payment: detailed.cuota_prestamo,
    investment_own_funds: detailed.inversiones_fondos_propios
  };
};

export const createEmptyDetailedYearlyData = (year: number): DetailedYearlyData => {
  return {
    year,
    ventas_netas: 0,
    valor_produccion: 0,
    comida: 0,
    comida_empleados: 0,
    desperdicios: 0,
    papel: 0,
    mano_obra: 0,
    mano_obra_gerencia: 0,
    seguridad_social: 0,
    gastos_viajes: 0,
    publicidad: 0,
    promocion: 0,
    servicios_exteriores: 0,
    uniformes: 0,
    suministros_operacion: 0,
    reparacion_mantenimiento: 0,
    luz_agua_telefono: 0,
    gastos_oficina: 0,
    diferencias_caja: 0,
    varios_controlables: 0,
    pac: 0,
    renta: 0,
    renta_adicional: 0,
    royalty: 0,
    oficina_legal: 0,
    seguros: 0,
    tasas_licencias: 0,
    depreciaciones_amortizaciones: 0,
    intereses: 0,
    perdidas_venta_equipos: 0,
    varios_no_controlables: 0,
    ventas_no_producto: 0,
    costo_no_producto: 0,
    draw_salary: 0,
    gastos_generales: 0,
    cuota_prestamo: 0,
    inversiones_fondos_propios: 0
  };
};
